# Generated by Django 4.2.7 on 2023-11-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('idWeights', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('weights', models.JSONField()),
            ],
        ),
    ]
