# Generated by Django 4.2.7 on 2023-11-24 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BackPropagation', '0004_backpropagation_classa_backpropagation_classb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backpropagation',
            name='date',
        ),
        migrations.AddField(
            model_name='backpropagation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
