# Generated by Django 4.2.7 on 2023-11-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackPropagation', '0005_remove_backpropagation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpropagation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
